#!/usr/bin/python
# -*- coding: utf-8 -*-

#################################################################################
# MIT License

# Copyright (c) 2022 Shun Nagao

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#################################################################################

import rospy
import rospkg

from geometry_msgs.msg import PoseWithCovarianceStamped
from geometry_msgs.msg import PoseStamped
from std_msgs.msg import String
import time
import os
import yaml

# global variables
publisher = None
rospack = rospkg.RosPack()

def goto(msg):
    global publisher
    global rospack

    with open(rospack.get_path('bamboobot') + "/spots/" + msg.data + ".yaml") as file:
        data = yaml.safe_load(file)
        x = data["position"]["x"]
        y = data["position"]["y"]
        z = data["position"]["z"]
        qx = data["orientation"]["x"]
        qy = data["orientation"]["y"]
        qz = data["orientation"]["z"]
        qw = data["orientation"]["w"]

        goal = PoseStamped()

        goal.header.stamp = rospy.Time.now()
        goal.header.frame_id = "map"

        goal.pose.position.x = x
        goal.pose.position.y = y
        goal.pose.position.z = z

        goal.pose.orientation.x = qx
        goal.pose.orientation.y = qy
        goal.pose.orientation.z = qz
        goal.pose.orientation.w = qw
        print(goal)

        publisher.publish(goal)

if __name__ == '__main__':
    rospy.init_node('goto_spot', log_level=rospy.DEBUG)

    # setting subscribers
    rospy.loginfo("setting subscribers...")
    rospy.Subscriber('bamboobot/goto_spot', String, goto)

    # setting publishers
    rospy.loginfo("setting publishers...")
    publisher = rospy.Publisher("move_base_simple/goal", PoseStamped, queue_size=1)

    r = rospy.Rate(10)
    while not rospy.is_shutdown():
        r.sleep()
